### ISSUE TITLE
"Guppy" -> "Guppys" instead of "Guppies" and others

### ISSUE THREAD

**Issue by Gheed0123** [jaraco/inflect#206] opened 2024-03-13 23:23 UTC
inflect.engine().plural_noun("Guppy") returns "Guppys"
inflect.engine().plural_noun("guppy") returns "guppies"

I manually fixed by removing capital letter at start: ''.join([txt[:1].lower(),txt[1:]])

and readding later with ''.join([txt[:1].upper(),txt[1:]])
string.capitalize() and string.lower() dont work in some cases

There might be another way, but I didnt bother looking

**Comment by jaraco** [comment] 2024-03-31 08:07
This looks like a duplicate of #201.

**Closed by jaraco** 2024-03-31 08:07 UTC
